services:
  frontend:
    build:
      context: ./frontend
    image: krokant/front_dom:latest
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - my_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - MQTT_SERVER=${MQTT_SERVER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPICS_MONITORING_CONDITION=${MQTT_TOPICS_MONITORING_CONDITION}
      - MQTT_TOKEN_AUTHORIZATION=${MQTT_TOKEN_AUTHORIZATION}
    image: krokant/backend_dom:latest
    ports:
      - "3001:5000"
    volumes:
      - ./backend:/app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
