version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    image: krokant/front_dom:latest
    ports:
      - "3000:80"  # React обычно работает на 3000
    volumes:
      - ./frontend:/app  # Монтируем код внутрь контейнера
      - /app/node_modules  # Исключаем node_modules, чтобы не было конфликтов
    networks:
      - my_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: krokant/backend_dom:latest
    ports:
      - "3001:5000"
    volumes:
      - ./backend:/app  # Монтируем код внутрь контейнера
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
